-- AS Survey System MVP SQLite schema
-- Generated by Genos on 2026-06-08
-- Source blueprint: /opt/data/cache/documents/as_survey_system_fixed.xlsx

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  region TEXT,
  phone TEXT,
  email TEXT,
  pin_hash TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('super_admin', 'as')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  last_login_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS branches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  branch_code TEXT NOT NULL UNIQUE,
  branch_name TEXT NOT NULL,
  account TEXT NOT NULL,
  region TEXT NOT NULL,
  province TEXT,
  assigned_user_id INTEGER NOT NULL REFERENCES users(id),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_branches_account_region_as ON branches(account, region, assigned_user_id);
CREATE INDEX IF NOT EXISTS idx_branches_search ON branches(branch_code, branch_name);

CREATE TABLE IF NOT EXISTS surveys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  survey_code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  category TEXT,
  description TEXT,
  deadline TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'closed', 'deleted')),
  created_by_user_id INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  published_at TEXT,
  closed_at TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TEXT,
  deleted_by_user_id INTEGER REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_surveys_status_deadline ON surveys(status, deadline);

CREATE TABLE IF NOT EXISTS survey_selected_branches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  survey_id INTEGER NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  selected_by_user_id INTEGER REFERENCES users(id),
  selected_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmed_at TEXT,
  UNIQUE (survey_id, branch_id)
);

CREATE TABLE IF NOT EXISTS survey_tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_code TEXT NOT NULL UNIQUE,
  survey_id INTEGER NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  assigned_user_id INTEGER NOT NULL REFERENCES users(id),
  deadline TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'pending', 'submitted', 'overdue', 'reopened')),
  assigned_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  submitted_at TEXT,
  last_updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (survey_id, branch_id)
);

CREATE INDEX IF NOT EXISTS idx_tasks_as_status ON survey_tasks(assigned_user_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_survey_status ON survey_tasks(survey_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_deadline ON survey_tasks(deadline);

CREATE TABLE IF NOT EXISTS survey_questions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  survey_id INTEGER NOT NULL REFERENCES surveys(id) ON DELETE CASCADE,
  question_code TEXT NOT NULL,
  question_order INTEGER NOT NULL,
  question_text TEXT NOT NULL,
  answer_type TEXT NOT NULL CHECK (answer_type IN ('short_text', 'long_text', 'number', 'single_choice', 'multiple_choice', 'photo')),
  required INTEGER NOT NULL DEFAULT 1 CHECK (required IN (0, 1)),
  allow_photo INTEGER NOT NULL DEFAULT 0 CHECK (allow_photo IN (0, 1)),
  photo_required INTEGER NOT NULL DEFAULT 0 CHECK (photo_required IN (0, 1)),
  options_json TEXT,
  help_text TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (survey_id, question_code),
  UNIQUE (survey_id, question_order),
  CHECK (photo_required = 0 OR allow_photo = 1)
);

CREATE INDEX IF NOT EXISTS idx_questions_survey_order ON survey_questions(survey_id, question_order);

CREATE TABLE IF NOT EXISTS survey_responses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  response_code TEXT NOT NULL UNIQUE,
  task_id INTEGER NOT NULL REFERENCES survey_tasks(id) ON DELETE CASCADE,
  submitted_by_user_id INTEGER NOT NULL REFERENCES users(id),
  submitted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edit_version INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_responses_task ON survey_responses(task_id);

CREATE TABLE IF NOT EXISTS survey_answers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  response_id INTEGER NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES survey_questions(id),
  answer_text TEXT,
  answer_number REAL,
  answer_json TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (response_id, question_id)
);

CREATE TABLE IF NOT EXISTS response_files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  file_code TEXT NOT NULL UNIQUE,
  response_id INTEGER NOT NULL REFERENCES survey_responses(id) ON DELETE CASCADE,
  answer_id INTEGER REFERENCES survey_answers(id) ON DELETE SET NULL,
  survey_id INTEGER NOT NULL REFERENCES surveys(id),
  task_id INTEGER NOT NULL REFERENCES survey_tasks(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  question_id INTEGER NOT NULL REFERENCES survey_questions(id),
  file_name TEXT NOT NULL,
  file_url TEXT,
  file_path TEXT,
  file_type TEXT,
  uploaded_by_user_id INTEGER NOT NULL REFERENCES users(id),
  uploaded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_files_response ON response_files(response_id);
CREATE INDEX IF NOT EXISTS idx_files_task ON response_files(task_id);

CREATE TABLE IF NOT EXISTS status_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  log_code TEXT NOT NULL UNIQUE,
  task_id INTEGER NOT NULL REFERENCES survey_tasks(id) ON DELETE CASCADE,
  survey_id INTEGER NOT NULL REFERENCES surveys(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  old_status TEXT,
  new_status TEXT NOT NULL,
  changed_by_user_id INTEGER REFERENCES users(id),
  changed_by_code TEXT,
  changed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note TEXT
);

CREATE INDEX IF NOT EXISTS idx_status_logs_task ON status_logs(task_id, changed_at);
CREATE INDEX IF NOT EXISTS idx_status_logs_survey ON status_logs(survey_id, changed_at);

CREATE TABLE IF NOT EXISTS admin_settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  setting_key TEXT NOT NULL UNIQUE,
  setting_value TEXT,
  description TEXT,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Useful progress view for admin dashboard.
CREATE VIEW IF NOT EXISTS survey_progress AS
SELECT
  s.id AS survey_id,
  s.survey_code,
  s.title,
  s.category,
  s.deadline,
  s.status,
  COUNT(t.id) AS total_assigned,
  SUM(CASE WHEN t.status = 'submitted' THEN 1 ELSE 0 END) AS submitted_count,
  SUM(CASE WHEN t.status <> 'submitted' THEN 1 ELSE 0 END) AS pending_count,
  SUM(CASE WHEN t.status <> 'submitted' AND date(t.deadline) < date('now') THEN 1 ELSE 0 END) AS overdue_count,
  CASE WHEN COUNT(t.id) = 0 THEN 0 ELSE ROUND(SUM(CASE WHEN t.status = 'submitted' THEN 1 ELSE 0 END) * 100.0 / COUNT(t.id), 1) END AS completion_pct,
  MAX(t.submitted_at) AS last_submitted_at
FROM surveys s
LEFT JOIN survey_tasks t ON t.survey_id = s.id
WHERE s.status <> 'deleted'
GROUP BY s.id;

-- Pending by AS for each survey.
CREATE VIEW IF NOT EXISTS survey_progress_by_as AS
SELECT
  s.id AS survey_id,
  s.survey_code,
  s.title AS survey_title,
  u.login_code AS as_code,
  u.name AS as_name,
  COUNT(t.id) AS assigned_count,
  SUM(CASE WHEN t.status = 'submitted' THEN 1 ELSE 0 END) AS submitted_count,
  SUM(CASE WHEN t.status <> 'submitted' THEN 1 ELSE 0 END) AS pending_count,
  CASE WHEN COUNT(t.id) = 0 THEN 0 ELSE ROUND(SUM(CASE WHEN t.status = 'submitted' THEN 1 ELSE 0 END) * 100.0 / COUNT(t.id), 1) END AS completion_pct,
  MAX(t.submitted_at) AS last_submitted_at
FROM surveys s
JOIN survey_tasks t ON t.survey_id = s.id
JOIN users u ON u.id = t.assigned_user_id
WHERE s.status <> 'deleted'
GROUP BY s.id, u.id;
